## Домашнее задание 1 (5 баллов)

Все задания ниже имеют равный вес (5/10).

### О задании

В этом домашнем задании вы попрактикуетесь в работе с библиотекой numpy, которая позволяет сравнительно легко и удобно выполнять разнообразные вычисления, избегая самостоятельной реализации поэлементной обработки.

Во всех задачах необходимо написать код решения внутри функции и убедиться, что она работает, с помощью [assert](https://python-reference.readthedocs.io/en/latest/docs/statements/assert.html) на выражение с использованием этой функции для данных из условия.

При решении задач запрещается использовать циклы (`for`, `while`) и оператор `if`. Да, `map`, `reduce`, `filter` и любые другие "чисто питоновские" конструкции тоже запрещены. **Используйте только функционал numpy**.

Везде, где встречаются массивы или матрицы, подразумевается, что это `numpy.array`.

**numpy reference:** https://numpy.org/doc/stable/reference/index.html

In [2]:
import numpy as np

### Задание 1

Напишите функцию, возвращающую округленную взвешенную сумму оценок по данным оценкам и весам. Можете посчитать свою оценку за курс :) В нашем случае вес экзамена равен 0.3, вес домашек - 0.4, вес контрольной - 0.2, вес самостоятельных - 0.1. Например, если за экзамен у вас 7, за домашки 10, за контрольную 8, а за самостоятельные 6, то вы получите отличную оценку 8!

Обратите внимание, что на вход приходит всегда двумерный массив. В нем в каждой строке - окенки одного конкретного студента. От вас требуется вернуть итоговую оценку для всех студентов в массиве.

In [102]:
def result_mark(weights: np.array, marks: np.array) -> int:
    raw_grade=np.average(marks, weights=weights,axis=1)
    return np.round(raw_grade).astype(int)
    # your code here

In [103]:
weights = np.array([0.3, 0.4, 0.2, 0.1])
marks = np.array([[7, 10, 8, 6], [6, 9, 7, 6]])

assert np.allclose(result_mark(weights, marks), np.array([8, 7]))

In [104]:
weights = np.array([0.3, 0.4, 0.2, 0.1])
marks = np.array([[7, 0, 8, 6]])

assert np.allclose(result_mark(weights, marks), np.array([4]))

### Задание 2

Напишите функцию, которая каждое четное число в массиве заменяет на его квадрат (вторую степень), а нечетное - на его синус. Округлите все значения в итоговом массиве до двух знаков после запятой.

In [18]:
def change_array(array: np.array) -> np.array:
  array=array.astype("float64")
  array[array%2==0]=array[array%2==0]**2
  array[array%2!=0]=np.sin(array[array%2!=0])
  return array.round(decimals=2)


In [19]:
array = np.array([2, 5, 1, 0, -6, 22, 213431])

assert np.allclose(change_array(array), np.array([4.0, -0.96, 0.84, 0.0, 36.0, 484.0, -0.58]))

In [20]:
array = np.array([3, 12, 15, -97, 6])

assert np.allclose(change_array(array), np.array([0.14, 144.0, 0.65, -0.38, 36.0]))

### Задание 3

Напишите функцию, которая вычисляет разность каждого элемента с предыдущим (для самого первого считайте, что его разница с "предыдущим" нулевая) в виде нового массива и возвращает вектор, в котором каждый новый элемент - сумма всех предыдущих из полученного нового массива.

In [28]:
def cumulative_sum_of_differences(array):
    array_1=np.append(array[0], array)
    return np.cumsum(array-array_1[:-1])

In [29]:
array = np.array([3, 6, 2, 8])

assert np.allclose(cumulative_sum_of_differences(array), np.array([0, 3, -1, 5]))

In [30]:
array = np.array([5, 1])

assert np.allclose(cumulative_sum_of_differences(array), np.array([0, -4]))

Вообще говоря, можно было в функции возвращать просто array-array[0], так как на i-том месте стоит a_i-a_{i-1}, а значит в векторе на i-том месте будет стоять телескопическая сумма (a_i-a_{i-1})+(a_{i-1}-a_{i-2})+...+(a_0-a_0)=a_i-a_0.

### Задание 4

Напишите функцию, которая транспонирует двумерный массив, затем делает из него одномерный (reshape), переводит все элементы массива в *int8* и выводит его отсортированным по убыванию.

In [36]:
def flatten_and_sort_transposed(array: np.array) -> np.array:
    array_transposed=np.transpose(array).flatten()
    return np.sort(array_transposed.astype("int8"))[::-1]
    # your code here

In [37]:
array = np.array([[256, -10], [-381, 112]])

assert np.allclose(flatten_and_sort_transposed(array), np.array([112, 0, -10, -125]))

In [38]:
array = np.array([[9, 8, 7], [3, 6, 129]])

assert np.allclose(flatten_and_sort_transposed(array), np.array([ 9, 8, 7, 6, 3, -127]))

### Задание 5

Напишите функцию, которая удаляет из массива все строки, среднее значение в которых больше общего среднего значения по всему массиву.

In [39]:
def filter_rows_by_mean(array):
    return array[np.average(array,axis=1)<=np.average(array)]
    # your code here

In [40]:
array = np.array([[1, 2, 3], [7, 8, 9], [4, 5, 6]])
res = filter_rows_by_mean(array)

assert res.ndim == 2
assert np.allclose(res, np.array([[1, 2, 3], [4, 5, 6]]))

In [41]:
array = np.array([[10, 20], [5, 5], [15, 15]])
res = filter_rows_by_mean(array)

assert res.ndim == 2
assert np.allclose(res, np.array([[5, 5]]))

### Задание 6

Напишите функцию, которая принимает на вход число - размер массива (квадратная матрица), который заполнен по принипу щахматной доски нулями и единицами. Первой (слева сверху) идет всегда единица. Напомним, что на шахматной доске белые и черные ячейки чередуются (в данном задании чередуются нули и единицы).

In [61]:
def create_checkerboard(number):
    indices=np.indices((number,number))
    return (indices[0]+indices[1]+1)%2
    # your code here

In [64]:
create_checkerboard(3)

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [65]:
number = 3

assert np.allclose(create_checkerboard(number) - np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]]), np.zeros((number, number)))

In [66]:
number = 4

assert np.allclose(create_checkerboard(number) - np.array([[1, 0, 1, 0], [0, 1, 0, 1], [1, 0, 1, 0], [0, 1, 0, 1]]), np.zeros((number, number)))

### Задание 7

Напишите функцию, которая соритрует строки двумерного массива по значению в первом (начиная с нуля) столбце (по возрастанию).

In [44]:
def sort_rows_by_second_column(array):
    return array[np.argsort(array[:,1])]

In [45]:
array = np.array([[10, 2], [3, 5], [7, 1]])

assert np.allclose(sort_rows_by_second_column(array), np.array([[7, 1], [10, 2], [3, 5]]))

In [46]:
array = np.array([[5, 8, 1], [10, 3, 9], [2, 7, 0], [6, -1, 5]])

assert np.allclose(sort_rows_by_second_column(array), np.array([[6, -1, 5], [10, 3, 9], [2, 7, 0], [5, 8, 1]]))

### Задание 8

Напишите функцию, которая вычисляет сумму элементов [побочной](https://ru.wikipedia.org/wiki/Квадратная_матрица) диагонали квадратной матрицы.

In [47]:
def sum_counterdiagonal_elements(array):
    return np.trace(np.rot90(array))

In [48]:
array = np.array([[5, 8, 1], [10, 3, 9], [2, 7, 0]])

assert sum_counterdiagonal_elements(array) == 6

In [49]:
array = np.array([[-4, -1, -1, 7], [6, -10, 5, -9], [3, -8, 6, 8], [-1, -6, 7, -10]])

assert sum_counterdiagonal_elements(array) == 3

### Задание 9

Напишите функцию, которая принимает на вход три числа (начало отрезка, конец отрезка, количество точек на отрезке). Данная функция генерирует указанное количество точек равномерно на отрезке с указанными концами (точки равноудалены друг от друга). Затем функция генерирует другой массив - натуральный логарифм от всех точек отрезка плюс единица ($ln(point + 1)$). Возвращает функция массив пар точек вида (точка на отрезке, ее логарифм). Каждое значение в возвращаемом массиве должно быть округлено до двух знаков после запятой.

In [80]:
def generate_logarithm_points(start, end, count):
    array=np.linspace(start,end, count, endpoint=True).round(decimals=2)
    array_log=np.log(array+1).round(decimals=2)
    return np.array(list(zip(array,array_log)))
    # your code here

In [81]:
generate_logarithm_points(1,10,5)


array([[ 1.  ,  0.69],
       [ 3.25,  1.45],
       [ 5.5 ,  1.87],
       [ 7.75,  2.17],
       [10.  ,  2.4 ]])

In [82]:
start = 1
end = 10
count = 5

assert np.allclose(generate_logarithm_points(start, end, count), np.array([[1., 0.69], [3.25, 1.45], [5.5 , 1.87], [7.75, 2.17], [10., 2.4]]))

In [83]:
generate_logarithm_points(5,12,4)

array([[ 5.  ,  1.79],
       [ 7.33,  2.12],
       [ 9.67,  2.37],
       [12.  ,  2.56]])

In [84]:
start = 5
end = 12
count = 4

assert np.allclose(generate_logarithm_points(start, end, count), np.array([[5., 1.79], [7.33, 2.12], [9.67, 2.37], [12., 2.56]]))

### Задание 10

Напишите функцию, которая нормализует входной двумерный массив.

Под нормализацией в данном задании подразумевается перевод всех чисел массива на отрезок $[0; 1]$. Очевидно, недостаточно просто вычесть/прибавить лишнее, чтобы остались числа на нужном отрезке. Суть нормализации массива в том, чтобы не потерять информацию о его элементах и их соотношениях. Потому, необходимо сохранить пропорции расстояний между каждым числом - спроецировать все точки на указанный отрезок. Такой метод масштабирования массива называется MinMaxScaling. Само название дает подсказку, как нужно решить задачу. Дробные числа округляйте до двух знаков после запятой.

*Будьте осторожны с делением...*

In [99]:
def min_max_scale(array):
    min=np.min(array)
    max=np.max(array)
    return np.where(max - min == 0, np.zeros(array.shape), ((array - min) / (max - min)).round(decimals=2)
    )
    # your code here

In [100]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

assert np.allclose(min_max_scale(array), np.array([[0. , 0.12, 0.25], [0.38, 0.5 , 0.62], [0.75, 0.88, 1.]]))

In [101]:
array = np.array([[0, 1, 2], [3, 4, 5]])

assert np.allclose(min_max_scale(array), np.array([[0., 0.2, 0.4], [0.6, 0.8, 1.]]))